### ISSUE TITLE
Computing derivatives with the DFT

### ISSUE THREAD

**Issue by mredenti** [boutproject/boututils#44]
I think there is a bug in the evaluation of the derivative using the DFT. In the line of code below, `n` should be replaced with the length of the domain `L` such that we are multiplying the DFT by `2 \pi k` where k are the ordinary wavenumbers/frequencies

https://github.com/boutproject/boututils/blob/2ae779e94b22a16f25c48eebe14340b43f46d0e1/boututils/calculus.py#L53

`n` is defined as 
https://github.com/boutproject/boututils/blob/2ae779e94b22a16f25c48eebe14340b43f46d0e1/boututils/calculus.py#L45
which would yield the number of points

I tested this on a simple trigonometric function

**Comment by ZedThree** [comment]
Fixed in #45
