### ISSUE TITLE
website?

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/boututils#6]
The website is set as `https://boutproject.github.io`, however that doesn't has anything on boututils.

Wouldn't `https://github.com/boutproject/boututils` be better?

**Comment by loeiten** [comment]
Good point. 

You are referring to the `pip`-package information, right? And I assume the same is also true for `boutdata`?

The only references I can see in `https://boutproject.github.io` are in the [Running BOUT++](https://bout-dev.readthedocs.io/en/latest/user_docs/running_bout.html?highlight=boututils) section and [Python routines](https://bout-dev.readthedocs.io/en/latest/user_docs/python.html?highlight=boututils#boututils). As these provide (at least) some information and ties the package to the BOUT++ project, it's possibly better to redirect there than no information on the `https://github.com/boutproject/boututils` page?

**Comment by dschwoerer** [comment]
Yes, this is for the pypi package.
Yes, probably also true for the boutdata package.

Both links you have mentioned are on readthedocs, not the main website.

I think the relevant sections are probably better then the main website. Although the info is very sparse, I am tempted to link here as we don't have any good documentation -.-
